MOUSEKEY_ENABLE = yes
OLED_ENABLE = no
OLED_DRIVER = ssd1306
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no
REPEAT_KEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
# TODO: MACRO
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no
