MCU = atmega32u4
BOOTLOADER = caterina

SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
MOUSEKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes

#SPACE SAVING
EXTRAKEY_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
LTO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

