CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = no
AUTOCORRECT_ENABLE = no
LEADER_ENABLE = no
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = no
OS_DETECTION_ENABLE = no
# unicode needs os specific?
UNICODE_COMMON = yes
UNICODE_ENABLE = yes
TAP_DANCE_ENABLE = no
